layout_spectrum: 0.056497344638377724
typography_spectrum: 0.6644395204075603
color:
  brandColors:
    - '#FFFFFF'
    - '#DC4648'
    - '#5E5E5E'
    - '#CE9A1C'
    - '#000000'
  brandStrength: 0.6692235960891599
  lightness: 0.0025684130124489567
  saturation: 0.6988053712169501
  rhythmicContrast: 0.7478125623548126
github: true
author:
  name: Manuel Blanco Appleby
  email: manuelblancoappleby@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e439cb5b-66a5-4161-83ea-7fe3591c6654.png
name: Dados a tu Favor
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Invitación
    id: e3e321c7-c730-4e31-b0a1-48e03c6109f6
    type: content
  - name: Filosofía
    id: 57f82557-4fab-45b2-8070-629bd8cfd3d6
    type: content
  - name: Visión
    id: 5cc82338-0e92-4411-a19e-313379809d02
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf187bcf-692d-4482-8863-d16cc4c8749d.png
title: Dados a tu favor
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Firma de Capital privado
purpose:
  - type: contact
    url: 'tel:447491204532'
    label: Teléfono
  - type: contact
    url: 'mailto:inversionistas@dadosatufavor.com'
    label: Email
