typography_spectrum: 0.28280528471805155
color:
  brandColors:
    - '#FFFFFF'
    - '#DC4648'
    - '#5E5E5E'
    - '#CE9A1C'
    - '#000000'
  brandStrength: 0.7399407455231994
  lightness: 0.0012651649303734303
  saturation: 0.7630845028907061
  rhythmicContrast: 0.2747214287519455
github: true
layout_spectrum: 0.057138227159157395
author:
  name: Manuel Blanco Appleby
  email: manuelblancoappleby@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e439cb5b-66a5-4161-83ea-7fe3591c6654.png
name: Dados a tu Favor
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: ¿Qué somos?
    id: fbfe1c8a-8a12-46d3-8575-e72bdc6837a2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf187bcf-692d-4482-8863-d16cc4c8749d.png
title: Dados a tu favor
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Firma de Capital privado
purpose:
  - type: contact
    url: 'tel:447491204532'
    label: 'Call '
  - type: contact
    url: 'mailto:inversionistas@dadosatufavor.com'
    label: Email
