name: Dados a tu Favor
layout_spectrum: 0.05131273112204479
typography_spectrum: 0.4860842032221579
color:
  brandColors:
    - '#FFFFFF'
    - '#DC4648'
    - '#5E5E5E'
    - '#CE9A1C'
    - '#000000'
  brandStrength: 0.664951866947594
  lightness: 0.003937554361280239
  saturation: 0.6981080615492814
  rhythmicContrast: 0.2704117144640572
purpose:
  - type: contact
    label: Email
    url: 'mailto:inversionistas@dadosatufavor.com'
title: Dados a tu favor
description: 'Firma Consultora en la industria FX, CFDs, CryptoAssets.'
author:
  name: Manuel Blanco Appleby
  email: manuelblancoappleby@gmail.com
navigation:
  - name: Invitación
    id: e3e321c7-c730-4e31-b0a1-48e03c6109f6
    type: content
  - name: Filosofía
    id: 57f82557-4fab-45b2-8070-629bd8cfd3d6
    type: content
  - name: Propuesta
    id: 5cc82338-0e92-4411-a19e-313379809d02
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/69e3bcf7-9bdf-4de8-88ea-bb33fa60df6c.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
